# Generated by Django 5.2.13 on 2026-05-05 12:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='license number')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MA', verbose_name='phone')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='location')),
                ('opens_at', models.TimeField(verbose_name='opens at')),
                ('closes_at', models.TimeField(verbose_name='closes at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'pharmacist'}, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pharmacy',
                'verbose_name_plural': 'pharmacies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalog.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharmacies.pharmacy')),
            ],
            options={
                'verbose_name': 'pharmacy stock',
                'verbose_name_plural': 'pharmacy stocks',
            },
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['is_active', 'is_verified'], name='pharmacies__is_acti_785e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacystock',
            index=models.Index(fields=['medicine', 'is_available'], name='pharmacies__medicin_cb480d_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacystock',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'medicine'), name='unique_pharmacy_medicine'),
        ),
    ]
