# Generated by Django 5.2.13 on 2026-05-05 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(verbose_name='starts at')),
                ('ends_at', models.DateTimeField(verbose_name='ends at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_shifts', to='pharmacies.pharmacy')),
            ],
            options={
                'verbose_name': 'night shift',
                'verbose_name_plural': 'night shifts',
                'ordering': ('-starts_at',),
                'indexes': [models.Index(fields=['pharmacy', 'starts_at'], name='pharmacies__pharmac_3711c3_idx'), models.Index(fields=['starts_at', 'ends_at'], name='pharmacies__starts__6bc4f3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='nightshift_ends_after_starts')],
            },
        ),
    ]
