# Generated by Django 5.2.13 on 2026-05-06 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_nightshift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nightshift',
            name='pharmacies__pharmac_3711c3_idx',
        ),
        migrations.AddField(
            model_name='nightshift',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who assigned this shift.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='nightshift',
            index=models.Index(fields=['pharmacy', 'starts_at', 'ends_at'], name='pharmacies__pharmac_d5e07a_idx'),
        ),
    ]
