# Generated by Django 5.2.16 on 2026-08-13 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryagentprofile_approved_at_and_more'),
        ('orders', '0004_orderstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('earning_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_offers', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_offers', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['agent', 'status'], name='delivery_de_agent_i_06db0e_idx'), models.Index(fields=['order', 'status'], name='delivery_de_order_i_4fcf49_idx'), models.Index(fields=['status', 'expires_at'], name='delivery_de_status_598725_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('agent',), name='delivery_one_pending_offer_per_agent'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('order',), name='delivery_one_pending_offer_per_order'), models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('order',), name='delivery_one_accepted_offer_per_order')],
            },
        ),
    ]
