# Generated by Django 5.2.16 on 2026-08-13 22:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryoffer'),
        ('orders', '0004_orderstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('return', 'Return')], max_length=20)),
                ('qr_token_hash', models.CharField(blank=True, max_length=128)),
                ('pin_hash', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(blank=True, choices=[('qr', 'QR code'), ('pin', 'PIN')], max_length=10)),
                ('verified_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_verifications', to='orders.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'delivery verification',
                'verbose_name_plural': 'delivery verifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['verification_type', 'expires_at'], name='delivery_de_verific_e078fd_idx'), models.Index(fields=['order', 'verification_type'], name='delivery_de_order_i_1d3f0e_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'verification_type'), name='unique_delivery_verification_per_order_type')],
            },
        ),
    ]
