# Generated by Django 5.2.16 on 2026-08-13 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliveryearning'),
        ('orders', '0004_orderstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('collection', 'COD collection'), ('settlement', 'Cash settlement'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed amount in MAD: collections are positive; settlements are negative.', max_digits=10)),
                ('currency', models.CharField(default='MAD', max_length=3)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_cash_transactions', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['agent', 'created_at'], name='delivery_ag_agent_i_f6ce11_idx'), models.Index(fields=['agent', 'transaction_type'], name='delivery_ag_agent_i_bc14e2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='agent_cash_transaction_amount_nonzero'), models.CheckConstraint(condition=models.Q(models.Q(('transaction_type', 'collection'), _negated=True), ('amount__gt', 0), _connector='OR'), name='agent_cash_collection_positive'), models.CheckConstraint(condition=models.Q(models.Q(('transaction_type', 'settlement'), _negated=True), ('amount__lt', 0), _connector='OR'), name='agent_cash_settlement_negative'), models.CheckConstraint(condition=models.Q(models.Q(('transaction_type', 'collection'), _negated=True), ('order__isnull', False), _connector='OR'), name='agent_cash_collection_requires_order'), models.UniqueConstraint(condition=models.Q(('transaction_type', 'collection')), fields=('order',), name='unique_agent_cash_collection_per_order')],
            },
        ),
    ]
