# Generated by Django 5.2.16 on 2026-08-14 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_agentcashtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MAD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.PROTECT, related_name='cash_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['agent', 'status'], name='delivery_ca_agent_i_a1b895_idx'), models.Index(fields=['agent', 'created_at'], name='delivery_ca_agent_i_564c9e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cash_settlement_amount_positive')],
            },
        ),
    ]
