# Generated by Django 5.2.16 on 2026-08-16 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_cashsettlement'),
        ('orders', '0004_orderstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('customer_unreachable', 'Customer unreachable'), ('customer_refused', 'Customer refused delivery'), ('wrong_address', 'Wrong address'), ('payment_issue', 'Payment issue'), ('delivery_pin_issue', 'Delivery PIN issue'), ('package_damaged', 'Package damaged'), ('package_missing', 'Package missing'), ('vehicle_problem', 'Temporary transport problem'), ('agent_emergency', 'Agent emergency'), ('unsafe_situation', 'Unsafe situation'), ('other', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved_continue', 'Resolved — continue delivery'), ('return_required', 'Return required'), ('returning', 'Returning to pharmacy'), ('returned', 'Returned to pharmacy'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('reported_order_status', models.CharField(help_text='Order status captured when the incident was reported.', max_length=32)),
                ('details', models.TextField(blank=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_incidents', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_incidents', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['order', 'status'], name='delivery_inc_order_status_idx'), models.Index(fields=['agent', 'status'], name='delivery_inc_agent_status_idx'), models.Index(fields=['status', 'created_at'], name='deliv_inc_status_created_idx')],
            },
        ),
    ]
