# Generated by Django 5.2.16 on 2026-08-17 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_deliveryapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryapplication',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='delivery_one_pending_application_per_user'),
        ),
    ]
