# Generated by Django 5.2.13 on 2026-05-07 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='action')),
                ('target_type', models.CharField(max_length=100, verbose_name='target type')),
                ('target_id', models.CharField(max_length=200, verbose_name='target id')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx'), models.Index(fields=['target_type', 'target_id', '-created_at'], name='audit_audit_target__edb7ad_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx')],
            },
        ),
    ]
