# Generated by Django 5.2.13 on 2026-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('generic_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='generic name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='manufacturer')),
                ('requires_prescription', models.BooleanField(default=False, verbose_name='requires prescription')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'medicine',
                'verbose_name_plural': 'medicines',
                'ordering': ('name',),
            },
        ),
    ]
