# Generated by Django 5.2.16 on 2026-08-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_placed', 'Order placed'), ('order_status_changed', 'Order status changed'), ('order_delivered', 'Order delivered'), ('order_cancelled', 'Order cancelled'), ('prescription_approved', 'Prescription approved'), ('prescription_rejected', 'Prescription rejected'), ('payment_succeeded', 'Payment succeeded'), ('payment_failed', 'Payment failed'), ('agent_assigned', 'Delivery agent assigned'), ('delivery_offer_available', 'Delivery offer available')], max_length=32),
        ),
    ]
